apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-example
  labels:
    app: config-example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: config-example-app
  template:
    metadata:
      labels:
        app: config-example-app
    spec:
      containers:
        - name: config-example-app
          image: brianbyers/configexample:latest
          ports:
            - containerPort: 8080